In [6]:
import numpy as np

#array of zero
print ('array of zero ',np.zeros([1,6]))
print()

#array of ones 
print(np.ones([4,6]))
print()

#array of stdout
print(np.empty(10))
print()

#array of given ranges and number of value.
print(np.linspace(1,10,num=20))


array of zero  [[0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[4.67296746e-307 1.69121096e-306 3.33772113e-307 2.67019456e-306
 1.42413555e-306 1.78019082e-306 1.37959740e-306 6.23057349e-307
 1.42419530e-306 1.42419530e-306]

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [2]:
#more than one dimension
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [3]:
#more than one dimension
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)
print(a.shape)

2
(3, 2)


In [8]:
a.view()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a.size


6

In [11]:
a.min()

1

In [12]:
a.max()

6

In [14]:
arr=np.array([[1,2,5,7,8,8,9]])
print(arr)

[[1 2 5 7 8 8 9]]


In [15]:
arr.mean()

5.714285714285714

In [16]:
arr.var()

8.489795918367346

In [17]:
arr.cumprod()

array([    1,     2,    10,    70,   560,  4480, 40320])

In [18]:
arr.cumsum()

array([ 1,  3,  8, 15, 23, 31, 40])

In [19]:
arr.data

In [9]:
print(range(10,20))

range(10, 20)


In [10]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [20]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
b=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]])
b.ndim

4

In [22]:
b.dtype

dtype('int32')

# dtype

In [1]:
#minimum dimension 

import numpy as np 

a=np.array([1,2,3,4,5], ndmin=3,dtype=str)
a

array([[['1', '2', '3', '4', '5']]], dtype='<U1')

In [12]:
import numpy as np 

a=np.array([1,2,3,4,5], ndmin=3,dtype=int)
a

array([[[1, 2, 3, 4, 5]]])

In [13]:
import numpy as np 

a=np.array([1,2,3,4,5], ndmin=3,dtype=float)# str,stroing ,object different way to write string 
a

array([[[1., 2., 3., 4., 5.]]])

In [14]:
#dtype parameter

import numpy as np 

a=np.array([1,2,3,4,5], ndmin=3,dtype=complex)
a

array([[[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]]])

In [19]:
#int2,int16,int32,int64 can be repalaced by equivalent string 'i1',i2,i4'

dt1= np.dtype('i4')
print(dt1)

int32


In [16]:

dt1= np.dtype('i2')
print(dt1)

int16


In [17]:
#we cannot fetch int 64
dt1= np.dtype('i1')
print(dt1)

int8


In [25]:
#first create structure data type 
dt =np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [24]:
#now apply it to ndarray object 
dt =np.dtype([('age',np.int8)])
a=np.array([(10,),(20,),(30,)], dtype =dt)
print(dt)

[('age', 'i1')]


In [26]:
#file name can bre used to access content of age column
dt =np.dtype([('age',np.int8)])
a=np.array([(10,),(20,),(30,)], dtype =dt)
print(a['age'])


[10 20 30]


In [34]:
student =np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [38]:
student =np.dtype([('name','S20'),('age','i1'),('marks','f4')])
st=np.array([('abc',21,40),('klm',18,50),('abc',21,40)], dtype=student)
print(st.shape)

(3,)


# Shape and reshape 

In [24]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [25]:
a.shape =(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [40]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
b=a.reshape(1,1,8,3)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]
   [ 9 10 11]
   [12 13 14]
   [15 16 17]
   [18 19 20]
   [21 22 23]]]]


4

In [28]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
#another way to conver 24
b=a.reshape(1,1,6,4)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


4

In [29]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
#another way to conver 24
b=a.reshape(2,2,3,2)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]


4

In [30]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
#another way to conver 24
b=a.reshape(3,2,2,2)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


4

In [31]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
#another way to conver 24
b=a.reshape(1,2,6,2)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]
   [ 8  9]
   [10 11]]

  [[12 13]
   [14 15]
   [16 17]
   [18 19]
   [20 21]
   [22 23]]]]


4

In [32]:
#this is one dimesnsional array 
import numpy as np

a=np.arange(24)
print(a)

#now reshape it 
#another way to conver 24
b=a.reshape(3,1,2,4)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0  1  2  3]
   [ 4  5  6  7]]]


 [[[ 8  9 10 11]
   [12 13 14 15]]]


 [[[16 17 18 19]
   [20 21 22 23]]]]


4

In [34]:
#dtype of array 
import numpy as np

x=np.array([1,2,3,4,5,6,9,10,10,12,15,14], dtype=np.float64)
print(x.itemsize)

8


# np.sort(),np.concatenate()

In [35]:
arr = np.array([1,2,3,4,5,6,7,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
a= np.array([1,2,3,4,])
b= np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])
np.concatenate((x,y),axis=0)#axis =0 is row wise concatenation 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])
np.concatenate((x,y),axis=1)#axis =1 iscolum wise concatenation

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
#for concat,data  and dimension should be equal then only we can do the concatenation 

# converting to 1d to 2d array 
np.newaxis,np.expand_dims

In [42]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a.ndim

1

In [50]:
a2=a[np.newaxis,0:5]
a2

array([[1, 2, 3, 4, 5]])

In [51]:
row_vector= a[np.newaxis,5:]

In [52]:
row_vector

array([[ 6,  7,  8,  9, 10]])

In [53]:
col_vector =a[5:, np.newaxis]
col_vector

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [54]:
a=np.array([1,2,3,6,8,9])
a

array([1, 2, 3, 6, 8, 9])

In [55]:
a.shape

(6,)

In [58]:
b=np.expand_dims(a,axis=0)
print(b.shape)

(1, 6)


In [59]:
b=np.expand_dims(a,axis=0)
print(b.shape)
print(b.ndim)

(1, 6)
2


In [60]:
print(b)

[[1 2 3 6 8 9]]


In [61]:
b=np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)
print(b)

(6, 1)
2
[[1]
 [2]
 [3]
 [6]
 [8]
 [9]]


# Indexing and slicing 

In [62]:
data =np.array([1,2,3])
print(data[1])
print(data[0:2:2])
print(data[1:])
print(data[-2:])

2
[1]
[2 3]
[2 3]


In [63]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
print(a[a>=7])

[ 7  8  9 10 11 12]


In [65]:
divisible_by2= a[a%2==0]

In [66]:
print(divisible_by2)

[ 2  4  6  8 10 12]


In [67]:
divisible_by2= a[a%2!=0]

In [68]:
print(divisible_by2)

[ 1  3  5  7  9 11]


In [70]:
c= a[(a>5) & (a<11)]
print(c)

[ 6  7  8  9 10]


In [71]:
c= a[(a>5) | (a<11)]
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:
c= a[(a>5) | (a==5)]
print(c)

[ 5  6  7  8  9 10 11 12]


In [73]:
a[2],b[0]

(array([ 9, 10, 11, 12]), array([1]))

# create an array from existing data
slicing and indexing ,np.vstack(),np.hstack(),np.hsplit()

# Linear algebra

In [5]:
import numpy as np 
#create a2x2 matrix

matrix=np.array([[1,3],
                [2,4]])

print("2x2 matrix:\n",matrix)


2x2 matrix:
 [[1 3]
 [2 4]]


In [6]:
#create 3x3 matrix

matrix1=np.array([[[1,2,6],
                  [2,3,4],
                  [6,7,8]]])
print(matrix1)

[[[1 2 6]
  [2 3 4]
  [6 7 8]]]


In [7]:
type(matrix1)

numpy.ndarray

In [25]:
#diagonal matrix
from numpy import array
import numpy as diag
M =array([[1,2,3],[4,6,2],[2,6,8]])
print(M)

[[1 2 3]
 [4 6 2]
 [2 6 8]]


In [15]:
#identity matrix
from numpy import identity
I=identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#cretate two matrix
matx1=np.array([[1,3],[5,7]])
matx2=np.array([[2,6],[4,8]])

#calculate the dot product of the two matrix

result=np.multiply(matx1,matx2)
print('multiply of vector:\n',result)

result=np.dot(matx1,matx2)
print('matx1 X matx2:\n',result)

multiply of vector:
 [[ 2 18]
 [20 56]]
matx1 X matx2:
 [[14 30]
 [38 86]]


# matrix -vector multiplication

In [43]:
#matrix -vector multiplication
from numpy import array
a = array([[1,2],[3,4],[5,6]])
print(a)
b = array([0.5,0.5])
print(b)
c=a.dot(b)
print(c)
d=a@b
print(d)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]
[1.5 3.5 5.5]


In [41]:
import numpy as np

array1= np.array([[1,3],
                  [5,7]])
array2 =np.array([[2,4],
                [6,8]])
result =np.inner(array1,array2)
print(result)

[[14 30]
 [38 86]]


In [39]:
import numpy as np
#define the coefficient matrix A
a=np.array([[2,4],
           [6,8]])
#define the constant vectort b
b=np.array([5,6])
#solve the system of linear equation ax=b
x=np.linalg.solve(a,b)
print(x)

[-2.    2.25]


# transpose of metrix

In [46]:
#create a matrix
mat1=np.array([[1,3],[5,7]])

#get transpose of mat1
result=np.transpose(mat1)
result_1= mat1.T

print(result)
print(result_1)

[[1 5]
 [3 7]]
[[1 5]
 [3 7]]


# inverse of matrix

In [48]:
#create matrix 

matrix1= np.array([[1,3,5],
                  [7,9,2],
                  [4,6,8]])
#find inverse of matrix 
result=np.linalg.inv(matrix1)
print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


# trace of matrix 

In [49]:
from numpy import trace
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(a)
b=trace(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


# determinant of matrix 


In [50]:
a=np.array([[1,2,3],
           [4,5,1],
           [2,3,4]])
print(a)
#find determinant of matrix
result=np.linalg.det(a)
print(result)

[[1 2 3]
 [4 5 1]
 [2 3 4]]
-4.999999999999999


In [ ]:
#Rank of deternimation

In [52]:
from numpy.linalg import matrix_rank
#rank
v1=np.array([1,2,3])
print(v1)
vr1=matrix_rank(v1)
print(vr1)
#zero rank
v2=np.array([0,0,0,0,0])
print(v2)
vr2=matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [57]:
a=np.array([[1,9,3],
           [4,5,1],
           [8,7,6]])
print(a)
#flatten opration
result=a.flatten()
print(result)

[[1 9 3]
 [4 5 1]
 [8 7 6]]
[1 9 3 4 5 1 8 7 6]


# set operation in numpy

In [53]:
#union
#intersection
#setdiffrence

In [54]:
a=np.array([1,3,5])
b=np.array([0,2,3])
#union 
result=np.union1d(a,b)
print(result)


[0 1 2 3 5]


# generating random value

In [58]:
#generating random value
random =np.random.randint(0,10)
print(random)

9


In [59]:
random =np.random.randint(100,1000)
print(random)

565


In [60]:
#generating 1d array of 5 random integer between 0 and 9
random =np.random.randint(0,10,5)
print(random)

[6 6 3 2 8]


In [63]:
#gerating 2d array of shape (3,4) with random integer
random =np.random.randint(0,10,(3,4))
print(random)

[[8 1 9 1]
 [2 0 2 4]
 [2 9 4 5]]


In [64]:
#create an array of integer from 1 to 5
array1=np.array([1,2,3,4,5])
#choose a random number from array1
random =np.random.choice(array1)
print(random)

4


# numpy interpolation

In [66]:
np.random.seed(10)
np.random.binomial(10,0.80,size=5)

array([ 7, 10,  8,  7,  8])

In [67]:
day=np.array([2,4,7])
gold_price=np.array([55,65,70])

#find the value of gold on 6th day or any day you required 
day_value=np.interp(6,day,gold_price)
print('the value of gold on 6th day:\n',day_value)

the value of gold on 6th day:
 68.33333333333333


In [68]:
day=np.array([2,4,7])
gold_price=np.array([55,65,70])

#find the value of gold on 6th day or any day you required 
day_value=np.interp(7,day,gold_price)
print('the value of gold on 7th day:\n',day_value)

the value of gold on 7th day:
 70.0


In [69]:
day=np.array([2,4,7])
gold_price=np.array([55,65,70])

#find the value of gold on 6th day or any day you required 
day_value=np.interp(8,day,gold_price)
print('the value of gold on 8th day:\n',day_value)

the value of gold on 8th day:
 70.0


In [74]:
# use datetime () for different time units 
year=np.datetime64('2023','Y')
month=np.datetime64('2023-04','M')
date=np.datetime64('2023-04-29','D')
#day=np.datetime64('2023-04-29 wed','day')
hour=np.datetime64('2023-04-29T10','h')
minute=np.datetime64('2023-04-29T10:30','M')
seconds=np.datetime64('2023-04-29T10:30:09','s')

print(year)
print(month)
print(date)
#print(day)
print(hour)
print(minute)
print(seconds)

2023
2023-04
2023-04-29
2023-04-29T10
2023-04
2023-04-29T10:30:09


In [75]:
#create a datetime object for today
today=np.datetime64('today')
#add one day to today date
tomorrow =today+ np.timedelta64(1,'D')
#create datetime object for two dates
date1=np.datetime64('2023-05-01')
date2=np.datetime64('2023-04-01')
#calculate the number days between the two dates 
num=date1-date2
#display 
print(today)
print(tomorrow)
print(num)

2023-12-04
2023-12-05
30 days


# numpy file I/O

In [ ]:
array1 = np.array([[2,4,6],[8,10,12]])

#save the array to a file 
np.save(file1.npy)